version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app


  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./services/postgres:/var/lib/postgresql/data/


volumes:
  postgres-data:
  nginx_secrets:


