version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis  # Указываем зависимость от Redis
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./services/postgres:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./services/redis:/data

volumes:
  postgres-data:
  nginx_secrets:
  redis-data:
